name: docker-build-push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Get the version
        id: vars
        run: |
          echo ::set-output name=tag::$(printf '%.2f\n' "$(echo "scale=2; $GITHUB_RUN_NUMBER * .01" | bc -l)")
          echo ::set-output name=previous-tag::$(printf '%.2f\n' "$(echo "scale=2; ($GITHUB_RUN_NUMBER - 1) * .01" | bc -l)")
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: truehostcloud/whmcs-apache-docker:${{steps.vars.outputs.tag}}-prod
          cache-from: type=registry,ref=truehostcloud/whmcs-apache-docker:${{steps.vars.outputs.previous-tag}}-prod
          cache-to: type=inline